version: '2'

includes:
  PROD: docker-compose.prod.yml

services:
  ui:
    build:
      context: ui
    image: thanhpk/sutu.shop:ui
    volumes:
      - "./ui:/srv/sutu.shop.ui"
    ports:
      - "8080:8080"
